name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Marker as <!-- EXAMPLE_START --><!-- EXAMPLE_END -->
      - name: Example 1 - multiple lines
        uses: gnpaone/dynamic-update-readme@v1.0.1
        with:
          marker_text: "EXAMPLE"
          markdown_text: |
            # Project Title

            ![Project Logo](https://via.placeholder.com/100)
            
            [![Example 1](https://img.shields.io/badge/Example%201-blue)]()
            [![Example 2](https://img.shields.io/badge/Example%202-red)]()
            
            ---
            
            ## Description
            
            A brief description of your project. Include your project's goals, the problem it solves, and how to use it.
            
            ## Table of Contents
            
            1. [Installation](#installation)
            2. [Usage](#usage)
            3. [Features](#features)
            4. [Contributing](#contributing)
            5. [License](#license)
            6. [Contact](#contact)
            
            ## Installation
            
            To install the project, follow these steps:
            
            ```bash
            git clone https://github.com/your-username/your-repo.git
            cd your-repo
            npm install
            ```
            
            ### Requirements
            
            - Node.js >= 18.0.0
            - npm >= 6.0.0
            
            ## Usage
            
            To use the project, run:
            
            ```bash
            npm start
            ```
            
            For additional options, use:
            
            ```bash
            npm run help
            ```
            
            ## Features
            
            - **Feature 1:** Brief description of feature 1.
            - **Feature 2:** Brief description of feature 2.
            - **Feature 3:** Brief description of feature 3.
            
            ### Screenshots
            
            ![Screenshot 1](https://via.placeholder.com/800x400)
            
            *Caption for Screenshot 1*
            
            ## Code Examples
            
            Here's a simple example of how to use a function in your project:
            
            ```javascript
            import { exampleFunction } from 'your-module';
            
            exampleFunction('Hello, World!');
            ```
            
            ## Configuration
            
            Adjust settings in the `config.json` file:
            
            ```json
            {
              "setting1": true,
              "setting2": "value",
              "setting3": [1, 2, 3]
            }
            ```
            
            ## Blockquotes
            
            > “The best way to predict the future is to create it.” – Peter Drucker
            
            ## Lists
            
            ### Unordered List
            
            - Item 1
              - Subitem 1.1
              - Subitem 1.2
            - Item 2
            - Item 3
            
            ### Ordered List
            
            1. First item
            2. Second item
            3. Third item
            
            ### Task List
            
            - [x] Task 1
            - [ ] Task 2
            - [ ] Task 3
            
            ## Tables
            
            | Feature        | Description                   | Status        |
            |----------------|:-----------------------------:|--------------:|
            | Feature 1      | Explanation of feature 1      | Complete      |
            | Feature 2      | Explanation of feature 2      | In Progress   |
            | Feature 3      | Explanation of feature 3      | Planned       |
            |<a href=""><img src="https://img.shields.io/badge/Example%201-blue" /></a>|<a href=""><img src="https://img.shields.io/badge/Example%202-red" /></a>|<a href=""><img src="https://img.shields.io/badge/Example%203-green" /></a>|
            
            ## Contributing
            
            Contributions are welcome! Please follow these steps:
            
            1. Fork the project.
            2. Create a new branch (`git checkout -b feature-branch`).
            3. Commit your changes (`git commit -m 'Add a feature'`).
            4. Push to the branch (`git push origin feature-branch`).
            5. Open a Pull Request.
            
            ## License
            
            This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.
            
            ## Contact
            
            Created by [Your Name](https://github.com/your-username) - feel free to contact me!
            
            - Email: your.email@example.com
            - Twitter: [@yourhandle](https://twitter.com/yourhandle)
            
            ## Acknowledgements
            
            - Thanks to [Contributor 1](https://github.com/contributor1)
            - Icons made by [Author](https://www.flaticon.com/authors/author) from [www.flaticon.com](https://www.flaticon.com)
            
            ---
            
            <sup>Copyright © 2024 [Your Name](https://github.com/your-username)</sup>

      # Marker as <!-- MARKER_TEXT_START --><!-- MARKER_TEXT_END -->
      - name: Example 2 - single line
        uses: gnpaone/dynamic-update-readme@v1.0.1
        with:
          marker_text: "MARKER_TEXT"
          markdown_text: "This is a sample text."
          confirm_and_push: "false"

      # Marker as <!-- TABLE_START --><!-- TABLE_END -->
      - name: Example 3 - add table
        uses: gnpaone/dynamic-update-readme@v1.0.1
        with:
          marker_text: "TABLE"
          table: "true"
          markdown_text: "<a href=''><img src='https://via.placeholder.com/100x25' /></a>,![placeholder](https://via.placeholder.com/100x25),[![image](https://via.placeholder.com/100x25)](https://via.placeholder.com);[![Example 1](https://img.shields.io/badge/Example%201-blue)](),[![Example 2](https://img.shields.io/badge/Example%202-red)](),<!-- PKG_START -->[![Example 3](https://img.shields.io/badge/Example%203-green)]()<!-- PKG_END -->;`code text`,More code text here:<br/>`more code text`,any text here"
          table_options: "col-0-align-left,col-1-align-center,col-2-align-right"
