name: Build
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.6'

      - name: Run lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Build
        run: |
          go get -d -v
          go build -v .
