name: Build
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: |
          go get -d -v
          go build -v .

      - name: Run lint
        uses: Jerome1337/golint-action@v1.0.2
        with:
          golint-path: .
