# This is a basic workflow to help you get started with Actions

name: Create tag

# Controls when the action will run. Triggers the workflow on push events
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v4

    # Commits all changed files to the repository
    - name: Commit to the repo
      run: |
        git config user.name "github-bot"
        git config user.email "github[bot]@gnpaone.github.io"
        git tag v1.0.1
        git push origin v1.0.1
